-- For these statements to run, close all other Query Editor windows

-- Examples
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

ALTER DATABASE AP SET ALLOW_SNAPSHOT_ISOLATION ON;

SET TRANSACTION ISOLATION LEVEL SNAPSHOT;

ALTER DATABASE AP SET READ_COMMITTED_SNAPSHOT ON;

-- Restore default settings
ALTER DATABASE AP SET ALLOW_SNAPSHOT_ISOLATION OFF;

ALTER DATABASE AP SET READ_COMMITTED_SNAPSHOT OFF;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


